
// This file has been generated by the GUI designer. Do not modify.
namespace CardGenerator
{
	public partial class DialogAddFaceData
	{
		private global::Gtk.VBox vbox2;
		private global::Gtk.Frame frame1;
		private global::Gtk.Alignment GtkAlignment2;
		private global::Gtk.ComboBox cbColumn;
		private global::Gtk.Label GtkLabel2;
		private global::Gtk.Frame frame2;
		private global::Gtk.Alignment GtkAlignment3;
		private global::Gtk.ComboBox cbLangCode;
		private global::Gtk.Label GtkLabel3;
		private global::Gtk.Frame frame3;
		private global::Gtk.Alignment GtkAlignment4;
		private global::Gtk.VBox vbox3;
		private global::Gtk.RadioButton rbText;
		private global::Gtk.RadioButton rbVoice;
		private global::Gtk.Label GtkLabel4;
		private global::Gtk.Button buttonCancel;
		private global::Gtk.Button buttonOk;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget CardGenerator.DialogAddFaceData
			this.Name = "CardGenerator.DialogAddFaceData";
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Internal child CardGenerator.DialogAddFaceData.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "dialog1_VBox";
			w1.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.frame1 = new global::Gtk.Frame ();
			this.frame1.Name = "frame1";
			this.frame1.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame1.Gtk.Container+ContainerChild
			this.GtkAlignment2 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment2.Name = "GtkAlignment2";
			this.GtkAlignment2.LeftPadding = ((uint)(12));
			// Container child GtkAlignment2.Gtk.Container+ContainerChild
			this.cbColumn = global::Gtk.ComboBox.NewText ();
			this.cbColumn.Name = "cbColumn";
			this.GtkAlignment2.Add (this.cbColumn);
			this.frame1.Add (this.GtkAlignment2);
			this.GtkLabel2 = new global::Gtk.Label ();
			this.GtkLabel2.Name = "GtkLabel2";
			this.GtkLabel2.LabelProp = global.Mono.Unix.Catalog.GetString ("Column");
			this.GtkLabel2.UseMarkup = true;
			this.frame1.LabelWidget = this.GtkLabel2;
			this.vbox2.Add (this.frame1);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.frame1]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.frame2 = new global::Gtk.Frame ();
			this.frame2.Name = "frame2";
			this.frame2.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame2.Gtk.Container+ContainerChild
			this.GtkAlignment3 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment3.Name = "GtkAlignment3";
			this.GtkAlignment3.LeftPadding = ((uint)(12));
			// Container child GtkAlignment3.Gtk.Container+ContainerChild
			this.cbLangCode = global::Gtk.ComboBox.NewText ();
			this.cbLangCode.AppendText (global.Mono.Unix.Catalog.GetString ("DA"));
			this.cbLangCode.AppendText (global.Mono.Unix.Catalog.GetString ("DE"));
			this.cbLangCode.AppendText (global.Mono.Unix.Catalog.GetString ("EN"));
			this.cbLangCode.AppendText (global.Mono.Unix.Catalog.GetString ("ES"));
			this.cbLangCode.AppendText (global.Mono.Unix.Catalog.GetString ("FR"));
			this.cbLangCode.AppendText (global.Mono.Unix.Catalog.GetString ("GA"));
			this.cbLangCode.AppendText (global.Mono.Unix.Catalog.GetString ("IT"));
			this.cbLangCode.AppendText (global.Mono.Unix.Catalog.GetString ("JA"));
			this.cbLangCode.AppendText (global.Mono.Unix.Catalog.GetString ("KO"));
			this.cbLangCode.AppendText (global.Mono.Unix.Catalog.GetString ("NL"));
			this.cbLangCode.AppendText (global.Mono.Unix.Catalog.GetString ("PL"));
			this.cbLangCode.AppendText (global.Mono.Unix.Catalog.GetString ("PT"));
			this.cbLangCode.AppendText (global.Mono.Unix.Catalog.GetString ("SV"));
			this.cbLangCode.AppendText (global.Mono.Unix.Catalog.GetString ("VB"));
			this.cbLangCode.AppendText (global.Mono.Unix.Catalog.GetString ("ZH"));
			this.cbLangCode.Name = "cbLangCode";
			this.cbLangCode.Active = 2;
			this.GtkAlignment3.Add (this.cbLangCode);
			this.frame2.Add (this.GtkAlignment3);
			this.GtkLabel3 = new global::Gtk.Label ();
			this.GtkLabel3.Name = "GtkLabel3";
			this.GtkLabel3.LabelProp = global.Mono.Unix.Catalog.GetString ("Language code");
			this.GtkLabel3.UseMarkup = true;
			this.frame2.LabelWidget = this.GtkLabel3;
			this.vbox2.Add (this.frame2);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.frame2]));
			w7.Position = 1;
			w7.Expand = false;
			w7.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.frame3 = new global::Gtk.Frame ();
			this.frame3.Name = "frame3";
			this.frame3.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame3.Gtk.Container+ContainerChild
			this.GtkAlignment4 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment4.Name = "GtkAlignment4";
			this.GtkAlignment4.LeftPadding = ((uint)(12));
			// Container child GtkAlignment4.Gtk.Container+ContainerChild
			this.vbox3 = new global::Gtk.VBox ();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.rbText = new global::Gtk.RadioButton (global.Mono.Unix.Catalog.GetString ("Text"));
			this.rbText.CanFocus = true;
			this.rbText.Name = "rbText";
			this.rbText.DrawIndicator = true;
			this.rbText.UseUnderline = true;
			this.rbText.Group = new global::GLib.SList (global::System.IntPtr.Zero);
			this.vbox3.Add (this.rbText);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.rbText]));
			w8.Position = 0;
			w8.Expand = false;
			w8.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.rbVoice = new global::Gtk.RadioButton (global.Mono.Unix.Catalog.GetString ("Voice"));
			this.rbVoice.CanFocus = true;
			this.rbVoice.Name = "rbVoice";
			this.rbVoice.DrawIndicator = true;
			this.rbVoice.UseUnderline = true;
			this.rbVoice.Group = this.rbText.Group;
			this.vbox3.Add (this.rbVoice);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.rbVoice]));
			w9.Position = 1;
			w9.Expand = false;
			w9.Fill = false;
			this.GtkAlignment4.Add (this.vbox3);
			this.frame3.Add (this.GtkAlignment4);
			this.GtkLabel4 = new global::Gtk.Label ();
			this.GtkLabel4.Name = "GtkLabel4";
			this.GtkLabel4.LabelProp = global.Mono.Unix.Catalog.GetString ("Voice/Text");
			this.GtkLabel4.UseMarkup = true;
			this.frame3.LabelWidget = this.GtkLabel4;
			this.vbox2.Add (this.frame3);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.frame3]));
			w12.Position = 2;
			w1.Add (this.vbox2);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(w1 [this.vbox2]));
			w13.Position = 0;
			// Internal child CardGenerator.DialogAddFaceData.ActionArea
			global::Gtk.HButtonBox w14 = this.ActionArea;
			w14.Name = "dialog1_ActionArea";
			w14.Spacing = 10;
			w14.BorderWidth = ((uint)(5));
			w14.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonCancel = new global::Gtk.Button ();
			this.buttonCancel.CanDefault = true;
			this.buttonCancel.CanFocus = true;
			this.buttonCancel.Name = "buttonCancel";
			this.buttonCancel.UseStock = true;
			this.buttonCancel.UseUnderline = true;
			this.buttonCancel.Label = "gtk-cancel";
			this.AddActionWidget (this.buttonCancel, -6);
			global::Gtk.ButtonBox.ButtonBoxChild w15 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w14 [this.buttonCancel]));
			w15.Expand = false;
			w15.Fill = false;
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonOk = new global::Gtk.Button ();
			this.buttonOk.CanDefault = true;
			this.buttonOk.CanFocus = true;
			this.buttonOk.Name = "buttonOk";
			this.buttonOk.UseStock = true;
			this.buttonOk.UseUnderline = true;
			this.buttonOk.Label = "gtk-ok";
			this.AddActionWidget (this.buttonOk, -5);
			global::Gtk.ButtonBox.ButtonBoxChild w16 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w14 [this.buttonOk]));
			w16.Position = 1;
			w16.Expand = false;
			w16.Fill = false;
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show ();
		}
	}
}
