
// This file has been generated by the GUI designer. Do not modify.
namespace CardGenerator
{
	public partial class Page0
	{
		private global::Gtk.VBox vbox5;
		private global::Gtk.Label label9;
		private global::Gtk.Button bnNewDB;
		private global::Gtk.Button bnLoadDB;
		private global::Gtk.Label labelFile;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget CardGenerator.Page0
			global::Stetic.BinContainer.Attach (this);
			this.Name = "CardGenerator.Page0";
			// Container child CardGenerator.Page0.Gtk.Container+ContainerChild
			this.vbox5 = new global::Gtk.VBox ();
			this.vbox5.Name = "vbox5";
			this.vbox5.Spacing = 6;
			this.vbox5.BorderWidth = ((uint)(6));
			// Container child vbox5.Gtk.Box+BoxChild
			this.label9 = new global::Gtk.Label ();
			this.label9.Name = "label9";
			this.label9.LabelProp = global.Mono.Unix.Catalog.GetString ("Select Database File");
			this.vbox5.Add (this.label9);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.label9]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.bnNewDB = new global::Gtk.Button ();
			this.bnNewDB.CanFocus = true;
			this.bnNewDB.Name = "bnNewDB";
			this.bnNewDB.UseUnderline = true;
			this.bnNewDB.Label = global.Mono.Unix.Catalog.GetString ("Create New...");
			this.vbox5.Add (this.bnNewDB);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.bnNewDB]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.bnLoadDB = new global::Gtk.Button ();
			this.bnLoadDB.CanFocus = true;
			this.bnLoadDB.Name = "bnLoadDB";
			this.bnLoadDB.UseUnderline = true;
			this.bnLoadDB.Label = global.Mono.Unix.Catalog.GetString ("Load existing...");
			this.vbox5.Add (this.bnLoadDB);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.bnLoadDB]));
			w3.Position = 2;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.labelFile = new global::Gtk.Label ();
			this.labelFile.Name = "labelFile";
			this.labelFile.LabelProp = global.Mono.Unix.Catalog.GetString ("File Selected: None");
			this.vbox5.Add (this.labelFile);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.labelFile]));
			w4.Position = 3;
			w4.Expand = false;
			w4.Fill = false;
			this.Add (this.vbox5);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
			this.bnNewDB.Clicked += new global::System.EventHandler (this.onBNNewDB);
			this.bnLoadDB.Clicked += new global::System.EventHandler (this.onBNLoadDB);
		}
	}
}
