
// This file has been generated by the GUI designer. Do not modify.
namespace CardGenerator
{
	public partial class Page5
	{
		private global::Gtk.VBox vbox1;
		private global::Gtk.Label label1;
		private global::Gtk.Button bnExportANKI;
		private global::Gtk.Button bnExportKleio;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget CardGenerator.Page5
			global::Stetic.BinContainer.Attach (this);
			this.Name = "CardGenerator.Page5";
			// Container child CardGenerator.Page5.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.LabelProp = global.Mono.Unix.Catalog.GetString ("Save Card Data");
			this.vbox1.Add (this.label1);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.label1]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.bnExportANKI = new global::Gtk.Button ();
			this.bnExportANKI.CanFocus = true;
			this.bnExportANKI.Name = "bnExportANKI";
			this.bnExportANKI.UseUnderline = true;
			this.bnExportANKI.Label = global.Mono.Unix.Catalog.GetString ("Export to ANKI CSV file...");
			this.vbox1.Add (this.bnExportANKI);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.bnExportANKI]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.bnExportKleio = new global::Gtk.Button ();
			this.bnExportKleio.CanFocus = true;
			this.bnExportKleio.Name = "bnExportKleio";
			this.bnExportKleio.UseUnderline = true;
			this.bnExportKleio.Label = global.Mono.Unix.Catalog.GetString ("Export to Kleio CSV file...");
			this.vbox1.Add (this.bnExportKleio);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.bnExportKleio]));
			w3.Position = 2;
			w3.Expand = false;
			w3.Fill = false;
			this.Add (this.vbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
			this.bnExportANKI.Clicked += new global::System.EventHandler (this.onBnExportANKI);
			this.bnExportKleio.Clicked += new global::System.EventHandler (this.onBnExportKLEIO);
		}
	}
}
