
// This file has been generated by the GUI designer. Do not modify.
namespace CardGenerator
{
	public partial class Page3
	{
		private global::Gtk.VBox vbox1;
		private global::Gtk.Label label1;
		private global::Gtk.Button buttonFolder;
		private global::Gtk.Button buttonRefresh;
		private global::Gtk.Button buttonDownload;
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		private global::Gtk.TreeView treeview1;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget CardGenerator.Page3
			global::Stetic.BinContainer.Attach (this);
			this.Name = "CardGenerator.Page3";
			// Container child CardGenerator.Page3.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.LabelProp = global.Mono.Unix.Catalog.GetString ("Generate Voice Files");
			this.vbox1.Add (this.label1);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.label1]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.buttonFolder = new global::Gtk.Button ();
			this.buttonFolder.CanFocus = true;
			this.buttonFolder.Name = "buttonFolder";
			this.buttonFolder.UseUnderline = true;
			this.buttonFolder.Label = global.Mono.Unix.Catalog.GetString ("Audio Folder: [Click to choose a folder]");
			this.vbox1.Add (this.buttonFolder);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.buttonFolder]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.buttonRefresh = new global::Gtk.Button ();
			this.buttonRefresh.CanFocus = true;
			this.buttonRefresh.Name = "buttonRefresh";
			this.buttonRefresh.UseUnderline = true;
			this.buttonRefresh.Label = global.Mono.Unix.Catalog.GetString ("Refresh");
			this.vbox1.Add (this.buttonRefresh);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.buttonRefresh]));
			w3.Position = 2;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.buttonDownload = new global::Gtk.Button ();
			this.buttonDownload.CanFocus = true;
			this.buttonDownload.Name = "buttonDownload";
			this.buttonDownload.UseUnderline = true;
			this.buttonDownload.Label = global.Mono.Unix.Catalog.GetString ("Download mp3s");
			this.vbox1.Add (this.buttonDownload);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.buttonDownload]));
			w4.Position = 3;
			w4.Expand = false;
			w4.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.treeview1 = new global::Gtk.TreeView ();
			this.treeview1.CanFocus = true;
			this.treeview1.Name = "treeview1";
			this.GtkScrolledWindow.Add (this.treeview1);
			this.vbox1.Add (this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.GtkScrolledWindow]));
			w6.Position = 4;
			this.Add (this.vbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
			this.buttonFolder.Clicked += new global::System.EventHandler (this.onBnFolder);
			this.buttonRefresh.Clicked += new global::System.EventHandler (this.onBnRefresh);
			this.buttonDownload.Clicked += new global::System.EventHandler (this.onBnDownload);
		}
	}
}
