
// This file has been generated by the GUI designer. Do not modify.
namespace CardGenerator
{
	public partial class Page2
	{
		private global::Gtk.VBox vbox6;
		private global::Gtk.Label label12;
		private global::Gtk.Frame frame1;
		private global::Gtk.Alignment GtkAlignment;
		private global::Gtk.HBox hbox1;
		private global::Gtk.ScrolledWindow GtkScrolledWindow1;
		private global::Gtk.TreeView treeviewCardType;
		private global::Gtk.VBox vbox1;
		private global::Gtk.Button bnCardTypeAdd;
		private global::Gtk.Button bnCardTypeRemove;
		private global::Gtk.Label GtkLabelA;
		private global::Gtk.Frame frame2;
		private global::Gtk.Alignment GtkAlignment1;
		private global::Gtk.HBox hbox2;
		private global::Gtk.ScrolledWindow GtkScrolledWindow2;
		private global::Gtk.TreeView treeviewFace1;
		private global::Gtk.VBox vbox2;
		private global::Gtk.Button bnFace1Add;
		private global::Gtk.Button bnFace1Remove;
		private global::Gtk.Label GtkLabel1A;
		private global::Gtk.Frame frame3;
		private global::Gtk.Alignment GtkAlignment2;
		private global::Gtk.HBox hbox3;
		private global::Gtk.ScrolledWindow GtkScrolledWindow3;
		private global::Gtk.TreeView treeviewFace2;
		private global::Gtk.VBox vbox3;
		private global::Gtk.Button bnFace2Add;
		private global::Gtk.Button bnFace2Remove;
		private global::Gtk.Label GtkLabel6;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget CardGenerator.Page2
			global::Stetic.BinContainer.Attach (this);
			this.Name = "CardGenerator.Page2";
			// Container child CardGenerator.Page2.Gtk.Container+ContainerChild
			this.vbox6 = new global::Gtk.VBox ();
			this.vbox6.Name = "vbox6";
			this.vbox6.Spacing = 6;
			// Container child vbox6.Gtk.Box+BoxChild
			this.label12 = new global::Gtk.Label ();
			this.label12.Name = "label12";
			this.label12.LabelProp = global.Mono.Unix.Catalog.GetString ("Card Structures");
			this.vbox6.Add (this.label12);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.label12]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vbox6.Gtk.Box+BoxChild
			this.frame1 = new global::Gtk.Frame ();
			this.frame1.Name = "frame1";
			this.frame1.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame1.Gtk.Container+ContainerChild
			this.GtkAlignment = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment.Name = "GtkAlignment";
			this.GtkAlignment.LeftPadding = ((uint)(12));
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
			this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
			this.treeviewCardType = new global::Gtk.TreeView ();
			this.treeviewCardType.CanFocus = true;
			this.treeviewCardType.Name = "treeviewCardType";
			this.GtkScrolledWindow1.Add (this.treeviewCardType);
			this.hbox1.Add (this.GtkScrolledWindow1);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.GtkScrolledWindow1]));
			w3.Position = 0;
			// Container child hbox1.Gtk.Box+BoxChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.bnCardTypeAdd = new global::Gtk.Button ();
			this.bnCardTypeAdd.CanFocus = true;
			this.bnCardTypeAdd.Name = "bnCardTypeAdd";
			this.bnCardTypeAdd.UseUnderline = true;
			this.bnCardTypeAdd.Label = global.Mono.Unix.Catalog.GetString ("Add...");
			this.vbox1.Add (this.bnCardTypeAdd);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.bnCardTypeAdd]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.bnCardTypeRemove = new global::Gtk.Button ();
			this.bnCardTypeRemove.CanFocus = true;
			this.bnCardTypeRemove.Name = "bnCardTypeRemove";
			this.bnCardTypeRemove.UseUnderline = true;
			this.bnCardTypeRemove.Label = global.Mono.Unix.Catalog.GetString ("Remove");
			this.vbox1.Add (this.bnCardTypeRemove);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.bnCardTypeRemove]));
			w5.Position = 1;
			w5.Expand = false;
			w5.Fill = false;
			this.hbox1.Add (this.vbox1);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.vbox1]));
			w6.Position = 1;
			w6.Expand = false;
			w6.Fill = false;
			this.GtkAlignment.Add (this.hbox1);
			this.frame1.Add (this.GtkAlignment);
			this.GtkLabelA = new global::Gtk.Label ();
			this.GtkLabelA.Name = "GtkLabelA";
			this.GtkLabelA.LabelProp = global.Mono.Unix.Catalog.GetString ("Card Type Name");
			this.GtkLabelA.UseMarkup = true;
			this.frame1.LabelWidget = this.GtkLabelA;
			this.vbox6.Add (this.frame1);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.frame1]));
			w9.Position = 2;
			// Container child vbox6.Gtk.Box+BoxChild
			this.frame2 = new global::Gtk.Frame ();
			this.frame2.Name = "frame2";
			this.frame2.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame2.Gtk.Container+ContainerChild
			this.GtkAlignment1 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment1.Name = "GtkAlignment1";
			this.GtkAlignment1.LeftPadding = ((uint)(12));
			// Container child GtkAlignment1.Gtk.Container+ContainerChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.GtkScrolledWindow2 = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow2.Name = "GtkScrolledWindow2";
			this.GtkScrolledWindow2.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow2.Gtk.Container+ContainerChild
			this.treeviewFace1 = new global::Gtk.TreeView ();
			this.treeviewFace1.CanFocus = true;
			this.treeviewFace1.Name = "treeviewFace1";
			this.GtkScrolledWindow2.Add (this.treeviewFace1);
			this.hbox2.Add (this.GtkScrolledWindow2);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.GtkScrolledWindow2]));
			w11.Position = 0;
			// Container child hbox2.Gtk.Box+BoxChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.bnFace1Add = new global::Gtk.Button ();
			this.bnFace1Add.CanFocus = true;
			this.bnFace1Add.Name = "bnFace1Add";
			this.bnFace1Add.UseUnderline = true;
			this.bnFace1Add.Label = global.Mono.Unix.Catalog.GetString ("Add...");
			this.vbox2.Add (this.bnFace1Add);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.bnFace1Add]));
			w12.Position = 0;
			w12.Expand = false;
			w12.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.bnFace1Remove = new global::Gtk.Button ();
			this.bnFace1Remove.CanFocus = true;
			this.bnFace1Remove.Name = "bnFace1Remove";
			this.bnFace1Remove.UseUnderline = true;
			this.bnFace1Remove.Label = global.Mono.Unix.Catalog.GetString ("Remove");
			this.vbox2.Add (this.bnFace1Remove);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.bnFace1Remove]));
			w13.Position = 1;
			w13.Expand = false;
			w13.Fill = false;
			this.hbox2.Add (this.vbox2);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.vbox2]));
			w14.Position = 1;
			w14.Expand = false;
			w14.Fill = false;
			this.GtkAlignment1.Add (this.hbox2);
			this.frame2.Add (this.GtkAlignment1);
			this.GtkLabel1A = new global::Gtk.Label ();
			this.GtkLabel1A.Name = "GtkLabel1A";
			this.GtkLabel1A.LabelProp = global.Mono.Unix.Catalog.GetString ("Face 1 (Front face)");
			this.GtkLabel1A.UseMarkup = true;
			this.frame2.LabelWidget = this.GtkLabel1A;
			this.vbox6.Add (this.frame2);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.frame2]));
			w17.Position = 3;
			// Container child vbox6.Gtk.Box+BoxChild
			this.frame3 = new global::Gtk.Frame ();
			this.frame3.Name = "frame3";
			this.frame3.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame3.Gtk.Container+ContainerChild
			this.GtkAlignment2 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment2.Name = "GtkAlignment2";
			this.GtkAlignment2.LeftPadding = ((uint)(12));
			// Container child GtkAlignment2.Gtk.Container+ContainerChild
			this.hbox3 = new global::Gtk.HBox ();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.GtkScrolledWindow3 = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow3.Name = "GtkScrolledWindow3";
			this.GtkScrolledWindow3.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow3.Gtk.Container+ContainerChild
			this.treeviewFace2 = new global::Gtk.TreeView ();
			this.treeviewFace2.CanFocus = true;
			this.treeviewFace2.Name = "treeviewFace2";
			this.GtkScrolledWindow3.Add (this.treeviewFace2);
			this.hbox3.Add (this.GtkScrolledWindow3);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.GtkScrolledWindow3]));
			w19.Position = 0;
			// Container child hbox3.Gtk.Box+BoxChild
			this.vbox3 = new global::Gtk.VBox ();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.bnFace2Add = new global::Gtk.Button ();
			this.bnFace2Add.CanFocus = true;
			this.bnFace2Add.Name = "bnFace2Add";
			this.bnFace2Add.UseUnderline = true;
			this.bnFace2Add.Label = global.Mono.Unix.Catalog.GetString ("Add...");
			this.vbox3.Add (this.bnFace2Add);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.bnFace2Add]));
			w20.Position = 0;
			w20.Expand = false;
			w20.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.bnFace2Remove = new global::Gtk.Button ();
			this.bnFace2Remove.CanFocus = true;
			this.bnFace2Remove.Name = "bnFace2Remove";
			this.bnFace2Remove.UseUnderline = true;
			this.bnFace2Remove.Label = global.Mono.Unix.Catalog.GetString ("Remove");
			this.vbox3.Add (this.bnFace2Remove);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.bnFace2Remove]));
			w21.Position = 1;
			w21.Expand = false;
			w21.Fill = false;
			this.hbox3.Add (this.vbox3);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.vbox3]));
			w22.Position = 1;
			w22.Expand = false;
			w22.Fill = false;
			this.GtkAlignment2.Add (this.hbox3);
			this.frame3.Add (this.GtkAlignment2);
			this.GtkLabel6 = new global::Gtk.Label ();
			this.GtkLabel6.Name = "GtkLabel6";
			this.GtkLabel6.LabelProp = global.Mono.Unix.Catalog.GetString ("Face 2 (Back face)");
			this.GtkLabel6.UseMarkup = true;
			this.frame3.LabelWidget = this.GtkLabel6;
			this.vbox6.Add (this.frame3);
			global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.frame3]));
			w25.Position = 4;
			this.Add (this.vbox6);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
			this.treeviewCardType.CursorChanged += new global::System.EventHandler (this.onCardTypeCursorChanged);
			this.bnCardTypeAdd.Clicked += new global::System.EventHandler (this.onBnCardTypeAdd);
			this.bnCardTypeRemove.Clicked += new global::System.EventHandler (this.onBnCardTypeRemove);
			this.bnFace1Add.Clicked += new global::System.EventHandler (this.onBnFace1Add);
			this.bnFace1Remove.Clicked += new global::System.EventHandler (this.onBnFace1Remove);
			this.bnFace2Add.Clicked += new global::System.EventHandler (this.onBnFace2Add);
			this.bnFace2Remove.Clicked += new global::System.EventHandler (this.onBnFace2Remove);
		}
	}
}
