
// This file has been generated by the GUI designer. Do not modify.
namespace CardGenerator
{
	public partial class Page1
	{
		private global::Gtk.VBox vbox1;
		private global::Gtk.Label label2;
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		private global::Gtk.TreeView treeview1;
		private global::Gtk.Button bnAddColumn;
		private global::Gtk.Button bnImportFromCSV;
		private global::Gtk.Button bnRemoveColumn;
		private global::Gtk.Button bnRemoveData;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget CardGenerator.Page1
			global::Stetic.BinContainer.Attach (this);
			this.Name = "CardGenerator.Page1";
			// Container child CardGenerator.Page1.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.label2 = new global::Gtk.Label ();
			this.label2.Name = "label2";
			this.label2.LabelProp = global.Mono.Unix.Catalog.GetString ("Translations Table");
			this.vbox1.Add (this.label2);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.label2]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.treeview1 = new global::Gtk.TreeView ();
			this.treeview1.CanFocus = true;
			this.treeview1.Name = "treeview1";
			this.GtkScrolledWindow.Add (this.treeview1);
			this.vbox1.Add (this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.GtkScrolledWindow]));
			w3.Position = 1;
			// Container child vbox1.Gtk.Box+BoxChild
			this.bnAddColumn = new global::Gtk.Button ();
			this.bnAddColumn.CanFocus = true;
			this.bnAddColumn.Name = "bnAddColumn";
			this.bnAddColumn.UseUnderline = true;
			this.bnAddColumn.Label = global.Mono.Unix.Catalog.GetString ("Add Column...");
			this.vbox1.Add (this.bnAddColumn);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.bnAddColumn]));
			w4.Position = 2;
			w4.Expand = false;
			w4.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.bnImportFromCSV = new global::Gtk.Button ();
			this.bnImportFromCSV.CanFocus = true;
			this.bnImportFromCSV.Name = "bnImportFromCSV";
			this.bnImportFromCSV.UseUnderline = true;
			this.bnImportFromCSV.Label = global.Mono.Unix.Catalog.GetString ("Import From CSV...");
			this.vbox1.Add (this.bnImportFromCSV);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.bnImportFromCSV]));
			w5.Position = 3;
			w5.Expand = false;
			w5.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.bnRemoveColumn = new global::Gtk.Button ();
			this.bnRemoveColumn.CanFocus = true;
			this.bnRemoveColumn.Name = "bnRemoveColumn";
			this.bnRemoveColumn.UseUnderline = true;
			this.bnRemoveColumn.Label = global.Mono.Unix.Catalog.GetString ("Remove Column...");
			this.vbox1.Add (this.bnRemoveColumn);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.bnRemoveColumn]));
			w6.Position = 4;
			w6.Expand = false;
			w6.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.bnRemoveData = new global::Gtk.Button ();
			this.bnRemoveData.CanFocus = true;
			this.bnRemoveData.Name = "bnRemoveData";
			this.bnRemoveData.UseUnderline = true;
			this.bnRemoveData.Label = global.Mono.Unix.Catalog.GetString ("Remove Data");
			this.vbox1.Add (this.bnRemoveData);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.bnRemoveData]));
			w7.Position = 5;
			w7.Expand = false;
			w7.Fill = false;
			this.Add (this.vbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
			this.bnAddColumn.Clicked += new global::System.EventHandler (this.onBnAddColumn);
			this.bnImportFromCSV.Clicked += new global::System.EventHandler (this.onBnImportFromCSV);
			this.bnRemoveColumn.Clicked += new global::System.EventHandler (this.onBnRemoveColumn);
			this.bnRemoveData.Clicked += new global::System.EventHandler (this.onBnRemoveData);
		}
	}
}
