
// This file has been generated by the GUI designer. Do not modify.
public partial class MainWindow
{
	private global::Gtk.VBox vbox4;
	private global::Gtk.EventBox eventBox;
	private global::Gtk.HBox hbox1;
	private global::Gtk.Button buttonPrevPage;
	private global::Gtk.Label labelPage;
	private global::Gtk.Button buttonNextPage;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global.Mono.Unix.Catalog.GetString ("Card Data Generator");
		this.Icon = global::Stetic.IconLoader.LoadIcon (this, "gtk-about", global::Gtk.IconSize.Menu);
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox4 = new global::Gtk.VBox ();
		this.vbox4.Name = "vbox4";
		this.vbox4.Spacing = 6;
		// Container child vbox4.Gtk.Box+BoxChild
		this.eventBox = new global::Gtk.EventBox ();
		this.eventBox.Name = "eventBox";
		this.vbox4.Add (this.eventBox);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.eventBox]));
		w1.Position = 1;
		// Container child vbox4.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox ();
		this.hbox1.Name = "hbox1";
		this.hbox1.Homogeneous = true;
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.buttonPrevPage = new global::Gtk.Button ();
		this.buttonPrevPage.CanFocus = true;
		this.buttonPrevPage.Name = "buttonPrevPage";
		this.buttonPrevPage.UseUnderline = true;
		this.buttonPrevPage.Label = global.Mono.Unix.Catalog.GetString ("Prev Page");
		this.hbox1.Add (this.buttonPrevPage);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.buttonPrevPage]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.labelPage = new global::Gtk.Label ();
		this.labelPage.Name = "labelPage";
		this.labelPage.LabelProp = global.Mono.Unix.Catalog.GetString ("Page #");
		this.hbox1.Add (this.labelPage);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.labelPage]));
		w3.Position = 1;
		w3.Expand = false;
		w3.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.buttonNextPage = new global::Gtk.Button ();
		this.buttonNextPage.CanFocus = true;
		this.buttonNextPage.Name = "buttonNextPage";
		this.buttonNextPage.UseUnderline = true;
		this.buttonNextPage.Label = global.Mono.Unix.Catalog.GetString ("Next Page");
		this.hbox1.Add (this.buttonNextPage);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.buttonNextPage]));
		w4.Position = 2;
		w4.Expand = false;
		w4.Fill = false;
		this.vbox4.Add (this.hbox1);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.hbox1]));
		w5.Position = 2;
		w5.Expand = false;
		w5.Fill = false;
		this.Add (this.vbox4);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 585;
		this.DefaultHeight = 483;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.buttonPrevPage.Clicked += new global::System.EventHandler (this.onBnPrevPage);
		this.buttonNextPage.Clicked += new global::System.EventHandler (this.onBnNextPage);
	}
}
